# Generated by Django 4.0.4 on 2022-04-27 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cakeshop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cake',
            name='berry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cake_berry', to='cakeshop.berry', verbose_name='Ягоды'),
        ),
        migrations.AlterField(
            model_name='cake',
            name='decoration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cake_decoration', to='cakeshop.decoration', verbose_name='Украшение'),
        ),
        migrations.AlterField(
            model_name='cake',
            name='inscription',
            field=models.CharField(blank=True, help_text='Надпись на торте', max_length=50, null=True, verbose_name='Надпись'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='referral',
            field=models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='cakeshop.advertisement', verbose_name='Реклама, по которой перешел пользователь'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('В обработке', 'В обработке'), ('Готовится', 'Готовится'), ('Доставлен', 'Доставлен')], db_index=True, max_length=255, verbose_name='Статус'),
        ),
    ]
