# Generated by Django 4.0.4 on 2022-05-01 07:34

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('cakeshop', '0003_customer_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phonenumber',
            field=phonenumber_field.modelfields.PhoneNumberField(help_text='+79987651244', max_length=50, region=None, verbose_name='Номер телефона'),
        ),
    ]
