# Generated by Django 4.0.4 on 2022-04-27 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakeshop', '0003_alter_berry_berry_alter_decoration_decoration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='berry',
            name='berry_codename',
            field=models.CharField(max_length=25, null=True, verbose_name='Кодовое имя топпинга'),
        ),
        migrations.AddField(
            model_name='decoration',
            name='decoration_codename',
            field=models.CharField(max_length=25, null=True, verbose_name='Кодовое имя топпинга'),
        ),
        migrations.AddField(
            model_name='shape',
            name='shape_codename',
            field=models.CharField(max_length=25, null=True, verbose_name='Кодовое имя формы'),
        ),
        migrations.AddField(
            model_name='topping',
            name='topping_codename',
            field=models.CharField(max_length=25, null=True, verbose_name='Кодовое имя топпинга'),
        ),
        migrations.AlterField(
            model_name='berry',
            name='berry',
            field=models.CharField(help_text='Клубника, голубика, ежевика, малина..', max_length=25, verbose_name='Ягода'),
        ),
        migrations.AlterField(
            model_name='decoration',
            name='decoration',
            field=models.CharField(help_text='Марципан, пекан, фундук, шоколадная крошка ..', max_length=10, verbose_name='Украшение'),
        ),
        migrations.AlterField(
            model_name='height',
            name='height',
            field=models.CharField(help_text='Высота торта в этажах (1, 2, 3 и т.д)', max_length=25, verbose_name='Высота'),
        ),
        migrations.AlterField(
            model_name='shape',
            name='shape',
            field=models.CharField(help_text='Форма торта (круг, шар, четырехмерный куб, бутылка Клейна и т.д)', max_length=25, verbose_name='Форма'),
        ),
        migrations.AlterField(
            model_name='topping',
            name='topping',
            field=models.CharField(help_text='Шоколадный, ванильный, медовый и т.д', max_length=25, verbose_name='Топпинг'),
        ),
    ]
