# Generated by Django 4.0.4 on 2022-05-02 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakeshop', '0004_alter_customer_phonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('В обработке', 'В обработке'), ('Ожидает оплаты', 'Ожидает оплаты'), ('Готовится', 'Готовится'), ('Доставлен', 'Доставлен')], db_index=True, default='В обработке', max_length=255, verbose_name='Статус'),
        ),
    ]
