# Generated by Django 4.0.4 on 2022-04-28 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakeshop', '0005_make_base_objs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='berry',
            name='berry_codename',
            field=models.CharField(max_length=25, null=True, verbose_name='Кодовое имя ягоды'),
        ),
        migrations.AlterField(
            model_name='cake',
            name='name',
            field=models.CharField(default='Без названия', help_text='Название', max_length=200, verbose_name='Название торта'),
        ),
        migrations.AlterField(
            model_name='decoration',
            name='decoration_codename',
            field=models.CharField(max_length=25, null=True, verbose_name='Кодовое имя украшения'),
        ),
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.PositiveIntegerField(verbose_name='Общая стоимость'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('В обработке', 'В обработке'), ('Готовится', 'Готовится'), ('Доставлен', 'Доставлен')], db_index=True, default='В обработке', max_length=255, verbose_name='Статус'),
        ),
    ]
