# Generated by Django 4.0.4 on 2022-05-02 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cakeshop', '0006_remove_customer_referral_order_referral'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='referral',
            field=models.ForeignKey(blank=True, max_length=255, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='cakeshop.advertisement', verbose_name='Реклама'),
        ),
    ]
