# Generated by Django 4.0.4 on 2022-04-28 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakeshop', '0006_alter_berry_berry_codename_alter_cake_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cake',
            name='description',
            field=models.CharField(blank=True, help_text='Описание', max_length=200, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='cake',
            name='name',
            field=models.CharField(default='Без названия', help_text='Название', max_length=200, null=True, verbose_name='Название торта'),
        ),
        migrations.AlterField(
            model_name='order',
            name='comment',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Комментарии'),
        ),
    ]
